replicaCount: 4
exposeHostPort: true
isClusterService: false
exposeHealthCheck: true
HealthCheckDomain: api.on-rio.io
image:
  repository: rancher/coredns
  tag: v1.5.0-rancher1-2-amd64
  pullPolicy: Always
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchExpressions:
        - key: app
          operator: In
          values:
          - coredns
      topologyKey: "kubernetes.io/hostname"
labels:
  app: coredns
servers:
- zones:
  - zone: .
  port: 53
  plugins:
  - name: rrl
    parameters: .
    configBlock: |-
      window 15
      ipv4-prefix-length 24
      ipv6-prefix-length 56
      responses-per-second 0
      nodata-per-second 10
      nxdomains-per-second 10
      referrals-per-second 10
      errors-per-second 10
      max-table-size 100000
  - name: file
    parameters: /etc/coredns/api.on-rio.io.dbfile api.on-rio.io
    configBlock: |-
      reload 0
  - name: etcd
    parameters: on-rio.io
    configBlock: |-
      path /rdns
      endpoint http://etcd-cluster:2379
      upstream 1.1.1.1:53 1.0.0.1:53
      wildcardbound 3
  - name: cache
    parameters: 600 on-rio.io api.on-rio.io
  - name: loadbalance
  - name: prometheus
    parameters: 0.0.0.0:9153
  - name: log
  - name: errors
  - name: health
zoneFiles:
  - filename: api.on-rio.io.dbfile
    domain: api.on-rio.io
    contents: |
      $ORIGIN api.on-rio.io.     ; designates the start of this zone file in the namespace
      $TTL 1h                           ; default expiration time of all resource records without their own TTL value
      @                                       IN  SOA      ns1.on-rio.io. on-rio.rancher.com. 1 3h 1h 1w 1h
      @                                       IN  A        35.160.108.90
      @                                       IN  A        52.88.130.113
      @                                       IN  A        52.43.109.53
      @                                       IN  A        54.70.74.111
