ebpf:
  # Enable eBPF support for Sysdig Agent
  enabled: true

  settings:
    # Needed to correctly detect the kernel version for the eBPF program
    # Set to false if not running on Google COS
    mountEtcVolume: false
sysdig:
  # Required: You need your Sysdig Monitor access key before running agents.
  accessKey: "fakekey"
  settings:
    ### Agent tags
    tags: RANCHER:bigmac,ENV:engineering,ROLE:example-onrio-io
    prometheus:
      enabled: true
      histograms: true
