replicaCount: 2
podAnnotations: {}
image:
  repository: rancher/rdns-server
  tag: v0.5.3-rancher-amd64
  pullPolicy: IfNotPresent
resources: {}
rdnsServerIngressHostname: api.on-rio.io
secret:
  name: rdnsserver
