apiVersion: v1
appVersion: 1.0.0
description: Deploys etcd cluster with etcd-operator
icon: https://github.com/rancher/ui/blob/master/public/assets/images/logos/welcome-cow.svg
name: etcd-operator-cluster
version: 0.0.1
