{{- if .Values.server.manifests }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "server.fullname" . }}-manifests
  labels:
    "app.kubernetes.io/name": '{{ template "server.name" .}}'
    "helm.sh/chart": "{{ .Chart.Name }}-{{ .Chart.Version }}"
    "app.kubernetes.io/managed-by": "{{ .Release.Service }}"
    "app.kubernetes.io/instance": "{{ .Release.Name }}"
data:
{{ toYaml .Values.server.manifests | indent 2 }}
{{- end }}
