{{ if .Values.secret.managed }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels:
    app: {{ include "slackin.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  slackApiToken: {{ .Values.secret.slackApiToken | b64enc | quote }}
  googleCaptchaSecret: {{ .Values.secret.googleCaptchaSecret | b64enc | quote }}
  googleCaptchaSiteKey: {{ .Values.secret.googleCaptchaSiteKey | b64enc | quote }}
{{ end }}
