apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "agent.name" . }}
  labels:
    {{ template "agent.name" . }}: "true"
    "app.kubernetes.io/name": '{{ template "agent.name" .}}'
spec:
  replicas: {{ .Values.agent.replicaCount }}
  selector:
    matchLabels:
      "app.kubernetes.io/name": '{{ template "agent.name" .}}'
  template:
    metadata:
      labels:
        {{ template "agent.name" . }}: "true"
        "app.kubernetes.io/name": '{{ template "agent.name" .}}'
    spec:
      containers:
        - name: k3s-agent
          env:
          - name: K3S_CLUSTER_SECRET
            value: {{ .Values.k3sClusterSecret }}
          - name: K3S_URL
            value: "https://{{ template "server.name" . }}:6443"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
              name: 80tcp
              protocol: TCP
            - containerPort: 443
              name: 443tcp
              protocol: TCP
          resources: {}
          securityContext:
            privileged: true
