{{ if .Values.agent.enableIngress }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "agent.name" . }}
  annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
      certmanager.k8s.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/secure-backends: "true"
spec:
  rules:
  - host: {{ .Values.agent.ingressHostname }}
    http:
      paths:
      - backend:
          serviceName: {{ template "agent.name" . }}
          servicePort: k3sagent80
  tls:
  - hosts:
    - {{ .Values.agent.ingressHostname }}
    secretName: {{ template "agent.name" . }}-ingress-cert
{{ end }}
