apiVersion: v1
kind: Service
metadata:
  name: {{ template "agent.name" . }}
  labels:
    {{ template "agent.name" . }}: "true"
spec:
  ports:
  - name: k3sagent80
    port: 80
    protocol: TCP
    targetPort: 80
  - name: k3sagent443
    port: 443
    protocol: TCP
    targetPort: 443
  type: ClusterIP
  selector:
    {{ template "agent.name" . }}: "true"
