apiVersion: v1
appVersion: 1.0.0
description: Runs etcd backup on cron
icon: https://github.com/rancher/ui/blob/master/public/assets/images/logos/welcome-cow.svg
name: etcd-cluster-backup
version: 0.0.1
