apiVersion: v1
kind: Service
metadata:
  name: {{ include "telemetry.fullname" . }}-tmp
  labels:
    app.kubernetes.io/name: {{ include "telemetry.name" . }}-tmp
    helm.sh/chart: {{ include "telemetry.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-tmp
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "telemetry.name" . }}-tmp
    app.kubernetes.io/instance: {{ .Release.Name }}-tmp
