apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rdns-server
  namespace: rdns-server
  annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
      certmanager.k8s.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/secure-backends: "true"
spec:
  # tls:
  #   - hosts:
  #     - test.onrio-dns.10.11.3.4.xip.io
  rules:
  - host: {{ .Values.rdnsServerIngressHostname }}
    http:
      paths:
      - backend:
          serviceName: rdns-server
          servicePort: 80
  tls:
  - hosts:
    - {{ .Values.rdnsServerIngressHostname }}
    secretName: api-on-rio-io-tls-cert
