apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rancherbot.fullname" . }}
  labels:
    {{- include "rancherbot.labels" . | nindent 4 }}
data:
  config.json: |
    {{ .Values.config | toJson }}
