apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rancherbot.fullname" . }}
  labels:
    {{- include "rancherbot.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "rancherbot.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "rancherbot.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "rancherbot.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag}}"
          volumeMounts:
          - name: token
            mountPath: "/etc/rancherbot/tokens"
            readOnly: true
          - name: config
            mountPath: "/etc/rancherbot/config"
            readOnly: true
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
      - name: token
        secret:
          secretName: {{ .Values.tokenSecretName }}
          defaultMode: 256
          items:
          - key: patoken
            path: patoken
          - key: webhooktoken
            path: webhooktoken
      - name: config
        configMap:
          name: {{ include "rancherbot.fullname" . }}
