apiVersion: v1
kind: ConfigMap
metadata:
  name: etcd-backup-config
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
data:
  etcd-configuration.json: |-
        {
          "cluster": {
            "leader": "{{ .Values.etcdEndpoint }}",
            "machines": [
              "{{ .Values.etcdEndpoint }}"
            ]
          },
          "config": {
            "certFile": "",
            "keyFile": "",
            "caCertFiles": [],
            "timeout": 10000000000000,
            "consistency": "STRONG"
          }
        }
  backup-configuration.json: |-
    {
      "concurrentRequests": 20
    }
