{{- if not .Values.etcdRestore }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: etcd-backup
spec:
  schedule: "{{ .Values.cronSchedule}}"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      # Cleaning jobs after 6h, same schedule period
      # Feature gated
      # ttlSecondsAfterFinished: {{ .Values.ttlSecondsAfterFinished }}
      # Job timeout
      activeDeadlineSeconds: {{ .Values.activeDeadlineSeconds }}
      template:
        spec:
          containers:
          - name: etcd-backup
            image: {{ .Values.image.name }}:{{ .Values.image.tag }}
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            args:
            - -c
            - backup
            - -r
            - {{ .Values.s3.path }}
            volumeMounts:
            - name: aws-config
              mountPath: /root/.aws
              readOnly: true
            - name: etcd-backup-config
              mountPath: /root/etcd-backup
              readOnly: true
          volumes:
            - name: aws-config
              secret:
                secretName: etcdbackupawscreds
            - name: etcd-backup-config
              configMap:
                name: etcd-backup-config
                items:
                - key: etcd-configuration.json
                  path: etcd-configuration.json
                - key: backup-configuration.json
                  path: backup-configuration.json
          # Do not restart pod, job takes care on restarting failed pod.
          restartPolicy: Never
{{ end }}
