{{- if .Values.etcdRestore }}
apiVersion: batch/v1
kind: Job
metadata:
  name: etcd-restore
spec:
  template:
    spec:
      containers:
      - name: etcd-restore
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        - -c
        - restore
        - -r
        - {{ .Values.s3.path }}
        volumeMounts:
        - name: aws-config
          mountPath: /root/.aws
          readOnly: true
        - name: etcd-backup-config
          mountPath: /root/etcd-backup
          readOnly: true
      volumes:
        - name: aws-config
          secret:
            secretName: etcdbackupawscreds
        - name: etcd-backup-config
          configMap:
            name: etcd-backup-config
            items:
            - key: etcd-configuration.json
              path: etcd-configuration.json
            - key: backup-configuration.json
              path: backup-configuration.json
      # Do not restart pod, job takes care on restarting failed pod.
      restartPolicy: Never

  backoffLimit: 4
{{ end }}
