apiVersion: "etcd.database.coreos.com/v1beta2"
kind: "EtcdCluster"
metadata:
  name: {{ .Values.name }}
  annotations:
    etcd.database.coreos.com/scope: clusterwide
spec:
  size: 3
  version: "3.2.18"
  pod:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "2379"
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: etcd_cluster
              operator: In
              values: ["{{ .Values.name }}"]
          topologyKey: kubernetes.io/hostname
