secret:
  name: telemetrysecrets
  # Set this to true if you want to manage these secrets with helm
  managed: false
  telemetryGaTid: ""
  telemetryPgPass: ""
  telemetryPgHost: ""

telemetryPgSSL: "require"
telemetryPort: 8115

replicaCount: 3

image:
  repository: rancher/telemetry
  tag: v0.6.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    prometheus.io/scrape: "true"
    prometheus.io/port: "10254"
  path: /
  hosts:
    - telemetry.rancher.io
  tls:
   - secretName: telemetry-rancher-io-tls
     hosts:
       - telemetry.rancher.io

resources:
  limits:
   cpu: 500m
   memory: 512Mi
  requests:
   cpu: 300m
   memory: 512Mi

nodeSelector: {}

tolerations: []

affinity: {}
