apiVersion: etcd.database.coreos.com/v1beta2
kind: EtcdBackup
metadata:
  name: etcd-cluster-backup
  namespace: etcd-operator
spec:
  backupPolicy:
    backupIntervalInSecond: 1800
    maxBackups: 336
  etcdEndpoints: ["http://etcd-cluster-client.{{ template "rdnsserver.name" . }}.svc:2379"]
  storageType: S3
  s3:
    path: {{ .Values.etcdBackupS3Bucket }}/etcd.backup.<NOW>
    awsSecret: {{.Values.etcdBackupAwsSecret }}
  storageType: S3
